[theme]
# Primary accent color for interactive elements.
primaryColor = "#ff6a4c"

# Background color for the main content area
backgroundColor = "#000000"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#ff6a4c"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarMode = "minimal"
